### ISSUE TITLE
1.20.1 Locking Empty Slots Crashes Client

### ISSUE THREAD

**Issue by BrandonJ98** [Tfarcenim/Dank-Storage#231] opened 2024-01-25 04:15 UTC
Dank Storage 5, Minecraft 1.20.1
Forge 47.2.16

Found in modpack All The Mods 9 version 0.2.33

Locking an empty slot in a dank storage causes a client crash to desktop due to a null pointer error. Please add a null check before locking slots. 

This is the exact error received:
'The game crashed whilst keypressed event handler
Error: java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "slot" is null'

**Comment by Tfarcenim** [comment] 2024-01-29 02:18
Duplicate of #227

**Closed as completed by Tfarcenim** 2024-01-29 02:18 UTC
