### ISSUE TITLE
Duping items indefinetly

### ISSUE THREAD

**Issue by DasOschi** [Tfarcenim/Dank-Storage#101] opened 2021-01-16 14:09 UTC
Hey Guys,

I've posted this issue on the [All the Mods 6] issues page already, but I guess it belongs here.
Since I don't wanna post everything again, here's the link: https://github.com/AllTheMods/ATM-6/issues/867

Tl;dr:
If your inventory has less slots than there are items on the ground you can just CTRL + Q the items you want to dupe out of your inventory. This works with storages such as chests or the ME system aswell. In large quantities (e.g. a full inventory of items) you can just Shift + Double Click the blocks into the inventory (e.g. the ME system) and the items on the ground won't disappear unless your inventory is emtpy and pick up the items without accessing an inventory of any form whilst standing of the mountain of items.

Clip of me duping items into an ME system: https://clips.twitch.tv/InterestingBlitheJuiceTheThing

Have a nice day =)

**Comment by Tfarcenim** [comment] 2021-01-16 14:22
Looks like you forced my hand

**Comment by Tfarcenim** [comment] 2021-01-16 14:41
Try reproducing with only dank storage

**Comment by DasOschi** [comment] 2021-01-16 14:46
I can give it a shot but only tomorrow since I'm streaming right now and was playing minecraft for 4 hours already ^^"

**Comment by flamingram** [comment] 2021-03-21 23:29
how did you do this im trying myself but cant reproduce??

**Comment by Tfarcenim** [comment] 2021-06-29 04:08
closing as not my problem

**Closed as completed by Tfarcenim** 2021-06-29 04:08 UTC
